pipeline {
    agent any
    	stages {
		stage ('Destroy App') {
			steps{
				sh (script: '''
                          #!/bin/bash
							COMPOSE_ID=${JOB_NAME:-local}
							# Remove Previous Stack
								docker-compose -p $COMPOSE_ID rm -f
							# Starting new stack environment
								docker-compose -p $COMPOSE_ID up -d --build
						''')
			 	}
			}  
		}
	}
