version: '3.4'

services:

  puppetclient:
    image: puppetclient-${PortNumber}
    container_name: puppetclient-${PortNumber}
    build: .
    extra_hosts:
      - "mohseen02.novalocal:10.20.14.212"
    links:
        - postgres
    environment:
        - DB_URL= postgresql://admin@postgresdb:5432/admin
        - PERSISTENCE_TYPE= postgres
    ports:
      - "${PortNumber}:8080"
  

  postgres:
    image: postgres:12.1
    container_name: postgresdb-${DBPortNumber}
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mypasswd
      - POSTGRES_DB=gidb
    ports:
        - "${DBPortNumber}:5432"
    volumes:
        - db-data:/var/lib/postgresql/data
  
volumes:
  db-data:

networks:
  gi_${PortNumber}