pipeline {
    agent any
    	stages {
		stage ('Building and running the container') {
			steps{
				sh (script: '''
                          	#!/bin/bash

							# Run the  Stack
							  DOCKER_HOST=“ssh://root@10.20.14.238” docker-compose up -d
						''')
			 	}
			}  
		stage ('Removing unused container images') {
			steps{
				sh (script: '''
                          	#!/bin/bash
                            docker system prune --all
						''')
			 	}
			} 
		}
	}
