pipeline {
    agent any
    	stages {
		stage ('Building and running the container') {
			steps{	      
                script {
                    sshagent(['6773d04f-2278-45f4-a937-1d2ef72f9ec6']) {
                        sh """
                            pwd
							export DOCKER_HOST=tcp://root@10.20.14.238:5555
							echo $DOCKER_HOST
							docker-compose up -d  
                        """
                	}
			 	}
			}  
		}
		stage ('Removing unused container images') {
			steps{
				sh (script: '''
                          	#!/bin/bash
                            docker system prune --all
						''')
			 	}
			} 
		}
	}
